!3 An exception in tearDown() of any added fixture is caught and displayed in the first table
!**< def
!define test (!|fitlibrary.SelectFixture|

!|add|fitlibrary.specify.select.SelectWithTearDownFailing|as|first|
!|add|fitlibrary.specify.select.SelectWithTearDownFailing|as|second|
)
**!
|!-fitlibrary.spec.SpecifyFixture-!|
|${test}|!-<table border="1" cellspacing="0">
<tr><td>fitlibrary.SelectFixture</td>
</tr>
</table>
<br/><table border="1" cellspacing="0">
<tr><td>add</td>
<td>fitlibrary.specify.select.SelectWithTearDownFailing</td>
<td>as</td>
<td>first</td>
</tr>
</table>
<table border="1" cellspacing="0">
<tr><td class="error">add<hr/> <span class="fit_label">tearDown errors</span></td>
<td>fitlibrary.specify.select.SelectWithTearDownFailing</td>
<td>as</td>
<td>second</td>
</tr>
</table>
-!|
