!3 An exception in setUp() of the added fixture is caught and displayed
!**< def
!define test (!|fitlibrary.SelectFixture|

!|add|fitlibrary.specify.select.SelectWithSetUpFailing|as|first|
)
**!
|!-fitlibrary.spec.SpecifyFixture-!|
|${test}|!-<table border="1" cellspacing="0">
<tr><td>fitlibrary.SelectFixture</td>
</tr>
</table>
<br/><table border="1" cellspacing="0">
<tr><td class="error">add<hr><pre><div class="fit_stacktrace"></div></pre></td>
<td>fitlibrary.specify.select.SelectWithSetUpFailing</td>
<td>as</td>
<td>first</td>
</tr>
</table>
-!|
